# docker-compose.yml (Umieść w głównym katalogu PTMS)

version: '3.8'

services:
  # 1. SERWIS BAZY DANYCH (PostgreSQL)
  db:
    image: postgres:15-alpine # Stabilny, lekki obraz DB
    container_name: ptms_db
    restart: always
    environment: # Zmienne konfiguracyjne dla obrazu Postgresa
      POSTGRES_DB: ptms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marek123
    ports:
      - "5432:5432" # Opcjonalne, ale przydatne do podglądu bazy
    volumes:
      - postgres_data:/var/lib/postgresql/data # Trwałość danych (nie stracisz ich po restarcie)
    healthcheck: # Sprawdzenie gotowości DB
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. SERWIS BACKENDU (PTMS - Aplikacja Spring Boot)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptms_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      # Teraz te nazwy (klucze po lewej) idealnie pasują do tego, co wpisaliśmy w ${...} w properties
      DB_URL: jdbc:postgresql://db:5432/ptms_db
      DB_USERNAME: postgres
      DB_PASSWORD: marek123

      # Zmienna dla Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: # Definicja wolumenu