spring.application.name=PTMS

# ----------------------------------------------------
# Ustawienia Połączenia JDBC (PostgreSQL)
# ----------------------------------------------------
# Czytamy ze zmiennej DB_URL (którą poda Docker). 
# Jeśli jej nie ma (np. w IntelliJ), używamy localhost (po dwukropku).
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ptms_db}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:marek123}

spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------------------
# Ustawienia JPA/Hibernate
# ----------------------------------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


