--
-- PostgreSQL database dump
--

\restrict bz67g0hYd7pzroGWjh03uK7lAs25SfmXZQ5gwC6EXwNvHDFObA64PfM5onCcQpU

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    trainer_id bigint
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan_exercises (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    reps_range character varying(255),
    rpe integer,
    sets integer,
    workout_day_id bigint
);


ALTER TABLE public.plan_exercises OWNER TO postgres;

--
-- Name: plan_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    body_weight double precision,
    completed boolean NOT NULL,
    end_time timestamp(6) without time zone,
    energy_level integer,
    notes character varying(255),
    sleep_quality integer,
    start_time timestamp(6) without time zone,
    stress_level integer,
    client_id bigint,
    workout_day_id bigint
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- Name: trainers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trainers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trainers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_days (
    id bigint NOT NULL,
    day_name character varying(255),
    focus character varying(255),
    workout_plan_id bigint
);


ALTER TABLE public.workout_days OWNER TO postgres;

--
-- Name: workout_days_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_plans (
    id bigint NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL,
    name character varying(255),
    client_id bigint
);


ALTER TABLE public.workout_plans OWNER TO postgres;

--
-- Name: workout_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, email, first_name, last_name, password, trainer_id) FROM stdin;
1	Kevinjeremiasz@gmail.com	Kevin	Jeremiasz	$2a$10$Y1H.Sf7lhxoG5q4K1RuOUOBNAr0h/0/RXUd/eQXbG0zHGji3.o1q.	1
2	RobertKalawski@gmail.com	Robert	Kalawski	$2a$10$n7vhi8V1ijQGwwEUYE/3P.rtoiVA5jCqDO6soY7PW2Aeessi9VfwG	2
4	BartekKlient@gmail.com	Bartosz	Testowy	$2a$10$XUuYXgF7cqgx37Skb1jy/uZ59Gkvm1hNHwSzeiWHE0sdeoF2hqSSi	\N
3	KacperJanik@gmail.com	Kacper	Janik	$2a$10$3QOtemjQtEamiCbd/ycex.l3IpnNVh50xiTgxt9fv/XOW/mJBqB6q	1
\.


--
-- Data for Name: plan_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plan_exercises (id, name, reps_range, rpe, sets, workout_day_id) FROM stdin;
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, body_weight, completed, end_time, energy_level, notes, sleep_quality, start_time, stress_level, client_id, workout_day_id) FROM stdin;
\.


--
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (id, email, first_name, last_name, password) FROM stdin;
1	MarekKuzbinski@gmail.com	Marek	Kuzbinski	$2a$10$Mj17cRPtJ6HR/QV61Id8uuCX2FiN5lw0m4pd/3xT9zAeInzO4UqpC
2	DawidTrener@gmail.com	Dawid	Wojciechowski	$2a$10$kZUP/KtnN.i8jfkox5rFBe.uiTP9u/G.E9/aTflGrGix5UG0O0Vj2
3	OskarTrener@gmail.com	Oskar	Trener	$2a$10$yqkmIm3up2Bw29tR3uA2ue1AR7D82zLzTwX5m7zFXv6GTY1vlmtDa
\.


--
-- Data for Name: workout_days; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_days (id, day_name, focus, workout_plan_id) FROM stdin;
\.


--
-- Data for Name: workout_plans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_plans (id, description, is_active, name, client_id) FROM stdin;
2	Tesst.	f	Plan trenignowy dla Barta	4
3	Drugi plan dla kevina tym razem opierajacy sie na sile pośladków.	f	Plan trenignowy dla Kevina 2	1
1	Plan skupia sie na budowie masy miesniowej i sile.	t	Plan trenignowy dla Kevina	1
\.


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 4, true);


--
-- Name: plan_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plan_exercises_id_seq', 1, false);


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 1, false);


--
-- Name: trainers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_id_seq', 3, true);


--
-- Name: workout_days_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_days_id_seq', 1, false);


--
-- Name: workout_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_plans_id_seq', 3, true);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: plan_exercises plan_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT plan_exercises_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: trainers trainers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainers_pkey PRIMARY KEY (id);


--
-- Name: trainers ukp760ma5h90yjnu0s0c94jawyb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT ukp760ma5h90yjnu0s0c94jawyb UNIQUE (email);


--
-- Name: clients uksrv16ica2c1csub334bxjjb59; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);


--
-- Name: workout_days workout_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT workout_days_pkey PRIMARY KEY (id);


--
-- Name: workout_plans workout_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT workout_plans_pkey PRIMARY KEY (id);


--
-- Name: clients fkflbm8oou4u4j1ely2kvnantwc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkflbm8oou4u4j1ely2kvnantwc FOREIGN KEY (trainer_id) REFERENCES public.trainers(id);


--
-- Name: plan_exercises fkicxqn7deurl719le4bogr6qwr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT fkicxqn7deurl719le4bogr6qwr FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: sessions fkn3wereisme2is39cxv0da3hjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkn3wereisme2is39cxv0da3hjw FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: workout_plans fknavqbtppjxedv2br0g2cxl944; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT fknavqbtppjxedv2br0g2cxl944 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: workout_days fknh09x2a6wbmvmjpqo7849vqan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT fknh09x2a6wbmvmjpqo7849vqan FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id);


--
-- Name: sessions fkqv5vmph05a8pscq0xg7vlfmj5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkqv5vmph05a8pscq0xg7vlfmj5 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bz67g0hYd7pzroGWjh03uK7lAs25SfmXZQ5gwC6EXwNvHDFObA64PfM5onCcQpU

