--
-- PostgreSQL database dump
--

\restrict uyjDlApNkzaFlySQIioqhJgFOyyo1lKCpyTKYDyU0m08NGyCRTD4Tf0UD6IAq5w

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    trainer_id bigint
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan_exercises (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    reps_range character varying(255),
    rpe integer,
    sets integer,
    workout_day_id bigint
);


ALTER TABLE public.plan_exercises OWNER TO postgres;

--
-- Name: plan_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    end_time timestamp(6) without time zone,
    notes character varying(255),
    start_time timestamp(6) without time zone,
    client_id bigint,
    workout_day_id bigint
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- Name: trainers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trainers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trainers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_days (
    id bigint NOT NULL,
    day_name character varying(255),
    focus character varying(255),
    workout_plan_id bigint
);


ALTER TABLE public.workout_days OWNER TO postgres;

--
-- Name: workout_days_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_plans (
    id bigint NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL,
    name character varying(255),
    client_id bigint
);


ALTER TABLE public.workout_plans OWNER TO postgres;

--
-- Name: workout_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, email, first_name, last_name, password, trainer_id) FROM stdin;
1	aa@gmail.com	aaa	aaa	$2a$10$8KsmylCAhIRhIz.R5rmH5euELZrB.3rnHhp.otx/TBA/yFkK3P6pK	\N
3	klient2@gmail.com	Klient2	test	$2a$10$4dzt2/A25E4X6ij7si9YOOwX9pkf0ZGcgcQupkY3yOLaa/2y6OHRm	\N
4	barbara123@gmail.com	Basia	Kuź	$2a$10$HVVmZWhcpT8CWG3mkduNDuOIXGklWB966IO/ty5EsKmNeIeGbqEx2	\N
5	Mirek@gmail.com	Mirek	Kuź	$2a$10$hdiHxndFo/235NUwCoWbU.HSgA.buLoVRjJq.et97ShFUPe0dYSBG	1
6	Kevintest@gmail.com	Kevin	Jeremiasz	$2a$10$XFJvCaa1bChRb8bbDiffn.BOZIVoR6VIdwG9rTdcHMsyiEivscBza	\N
\.


--
-- Data for Name: plan_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plan_exercises (id, name, reps_range, rpe, sets, workout_day_id) FROM stdin;
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, completed, end_time, notes, start_time, client_id, workout_day_id) FROM stdin;
\.


--
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (id, email, first_name, last_name, password) FROM stdin;
1	adam.nowak@trener.com	Adam	Nowak	$2a$10$4UGGgdSLWxM5lnWp6GsWWewqXIOROQOBSkgN24iaPW4C9opfGkNbG
2	Trenerkamil@gmail.com	Kamil	test	$2a$10$yuvQmN9IrBLT/dAdruN2auoEPCfzLQZqwO7aPDaV9DONTKFPoM6nq
3	TrenerOskar@gmail.com	Oskar	trenmer	$2a$10$ob8wgyqU4UT7e2CuJysq1OrZx/aMTDvFU7bDHoA2l8ofXHd5kLLTe
\.


--
-- Data for Name: workout_days; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_days (id, day_name, focus, workout_plan_id) FROM stdin;
\.


--
-- Data for Name: workout_plans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_plans (id, description, is_active, name, client_id) FROM stdin;
\.


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 6, true);


--
-- Name: plan_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plan_exercises_id_seq', 1, false);


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 1, false);


--
-- Name: trainers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_id_seq', 3, true);


--
-- Name: workout_days_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_days_id_seq', 1, false);


--
-- Name: workout_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_plans_id_seq', 1, false);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: plan_exercises plan_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT plan_exercises_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: trainers trainers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainers_pkey PRIMARY KEY (id);


--
-- Name: trainers ukp760ma5h90yjnu0s0c94jawyb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT ukp760ma5h90yjnu0s0c94jawyb UNIQUE (email);


--
-- Name: clients uksrv16ica2c1csub334bxjjb59; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);


--
-- Name: workout_days workout_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT workout_days_pkey PRIMARY KEY (id);


--
-- Name: workout_plans workout_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT workout_plans_pkey PRIMARY KEY (id);


--
-- Name: clients fkflbm8oou4u4j1ely2kvnantwc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkflbm8oou4u4j1ely2kvnantwc FOREIGN KEY (trainer_id) REFERENCES public.trainers(id);


--
-- Name: plan_exercises fkicxqn7deurl719le4bogr6qwr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT fkicxqn7deurl719le4bogr6qwr FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: sessions fkn3wereisme2is39cxv0da3hjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkn3wereisme2is39cxv0da3hjw FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: workout_plans fknavqbtppjxedv2br0g2cxl944; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT fknavqbtppjxedv2br0g2cxl944 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: workout_days fknh09x2a6wbmvmjpqo7849vqan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT fknh09x2a6wbmvmjpqo7849vqan FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id);


--
-- Name: sessions fkqv5vmph05a8pscq0xg7vlfmj5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkqv5vmph05a8pscq0xg7vlfmj5 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- PostgreSQL database dump complete
--

\unrestrict uyjDlApNkzaFlySQIioqhJgFOyyo1lKCpyTKYDyU0m08NGyCRTD4Tf0UD6IAq5w

